### ISSUE TITLE
Very high Perplexity for the generated texts

### ISSUE THREAD

**Issue by kirudang** [jthickstun/watermark#7]
Hello,

I am using generate.py to generate watermarked outputs from OPT 125M and Llama 2 7B.
This is my parameters for original set up without watermark:

```
outputs = model.generate(
        prompt_tokens,
        max_new_tokens = 200)
```

There is no setting for Temperature, Top K,...
And this is the code for your watermark, in which m = 200, max_input = 200 (both take the first 200 tokens from text) and let the models generate next max 200 tokens. I also print out to check 2 experiments are equivalent.

```
        prompt_tokens = tokenizer.encode(prompt, return_tensors="pt", truncation=True, max_length=max_inp).to(device)
        prompt_tokens = prompt_tokens.cuda()
        generated_prompt = tokenizer.batch_decode(prompt_tokens, skip_special_tokens=True)[0]
        
        # # Print number of tokens in generated_prompt
        # print(f'Number of tokens in generated_prompt: {len(tokenizer.encode(generated_prompt))}')

        # Generate the next 200 tokens
        outputs = generate_shift(model, prompt_tokens, len(tokenizer), args.n, args.m, args.key)[0]

        # Decode the generated output
        generated_text = tokenizer.decode(outputs, skip_special_tokens=True)

```
But when i check the PPL, here is the result:
OPT 125M without wm: 2.84116768836975
OPT 125M with your wm: 44.7086524963378

Llama 2 7B without wm: 2.993031502
Llama 2 7B with your wm: 5.67812490463256

With Distortion-free property, i guess the PPL should maintain? 
And there is any flexibility that we could control the outputs by adjust model parameters?

Thank you.

**Comment by jthickstun** [comment]
Hi @kirudang. The problem is that you're using [greedy decoding](https://huggingface.co/docs/transformers/generation_strategies#greedy-search) for the baseline. To get a sample from the model, you need to set `do_sample=True`. To match the watermarked generate function, you'll also need to set `top_k=0`. Sampling without a watermark:

```
outputs = model.generate(prompt_tokens, max_new_tokens = 200, do_sample=True, top_k=0)
```

Note that our watermark will not be detectable in greedy decoded outputs, as this decoding strategy is deterministic and therefore independent of the watermark key.
