### ISSUE TITLE
z-scores test_stat function for Kirchenbauer method

### ISSUE THREAD

**Issue by SecureDL** [jthickstun/watermark#8]
Hi.
Thank you for sharing your codes with us. I have a question regarding your setup for the following function:
```
def test_stat_wrapper(tokens):
      try:
          return torch.tensor(-watermark_detector.detect(tokenizer.decode(tokens, skip_special_tokens=True))['z_score'])
      except:
          return torch.tensor(0.0)
```
My first question here is why are you negating the returned z-scores? I am not very familiar on how to extract p values from z-scores, so there could something missing on my side.
Also, why it's important to run the n_runs loop if we are going to use different examples in the following loops?

Thanks.

**Comment by RohithKuditipudi** [comment]
Hi, sorry for the belated reply! The reason we return the negated z-scores is because in our framework we interpret low values of the test statistic to indicate watermarked text. This was a completely arbitrary design decision that happens to be inconsistent with Kirchenbauer et al. (where higher z-scores indicate watermarked text).

I'm not sure I understand the second part of your question. Would you mind clarifying?

> Also, why it's important to run the n_runs loop if we are going to use different examples in the following loops?

**Comment by SecureDL** [comment]
Thank you so much for your reply. For my second question, I think it's clear now. I will close this now.
